name: Test root

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-root:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repository (shallow)
        uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint-docs

