name: Test answer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-answer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: answers/clean-architecture/data-crossing-boundaries-enlarge-database/code/problem/node-hapi/problem

    container: node:10.18-jessie
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: oiga
          POSTGRES_HOST_AUTH_METHOD: trust
        # Wait until DB respond to requests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: checkout repository (shallow)
        uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm run test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: oiga
